#playbook is list of plays, always it should start with -(hypen)
- name: ping the node
  hosts: node1
  # this is list of tasks/modules/collections
  tasks:
  - name: pinging the server
    # this is the map
    ansible.builtin.ping:



# ansible-playbook -i inventory-location -e ansible_user=centos -e ansible_password=DevOps321 01-playbook.yaml

# ansible-playbook -i inventory-location -u centos --ask-pass 01-playbook.yaml

# ansible-playbook -i 172.31.94.215, all -e ansible_user=centos -e ansible_password=DevOps321 01-playbook.yaml