- name: play level variables in ansible
  hosts: node1
  # this ia play level variable ; MAP
  vars:
    course: devops with aws
    trainer: siva

  tasks:
  - name: printing play level variables
    ansible.builtin.debug:
      msg: "hello i am learning {{course}}"