- name: task level variables
  hosts: localhost
  vars: 
    money: "10000$"
    land: "10 hectors"
    where: play-level
  tasks:
  - name: inheritance and printing variables from task level
    vars:
      land: "5 hectors"
      money: "5000$"
      level: "task-level" 
    ansible.builtin.debug:
      msg: "land={{land}};cost={{money}};level={{level}};where={{where}}"
