# number
# string
# list
# map
# boolean

- name: ansible data types
  hosts: localhost

  vars:
  - age: 25 # number
  - NAME: "suresh" # string
  - male: true # boolean
  - skills:
    - DevOps
    - AWS
    - Docker
    - Terraform
  - experience: # map
      devops: 7
      aws: 5
  
  tasks:
  - name: print number data type
    ansible.builtin.debug:
      msg: "{{age}}"
  - name: print string data type
    ansible.builtin.debug:
      msg: "{{NAME}}"
  - name: print boolean data type
    ansible.builtin.debug:
      msg: "{{male}}"
  - name: print map data type
    ansible.builtin.debug:
      msg: "{{experience}}"
  - name: print list data type
    ansible.builtin.debug:
      msg: "{{skills}}"
    